### ISSUE TITLE
can't backup _users database

### ISSUE THREAD

**Issue by sballesteros** [cloudant/couchbackup#253] opened 2018-10-11 03:00 UTC
## Bug Description

Trying to backup the _users DB from the cloudant developer docker image (https://hub.docker.com/r/ibmcom/cloudant-developer/) result in a crash. Maybe _bulk_get is not implemented for `_users` ? the docker image seems pretty old and out of date.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

run 

```sh
couchbackup --url http://admin:pass@127.0.0.1:5984 --db _users
```

### 2. What you expected to happen

backup of the `_users` database

### 3. What actually happened

a TypeError:

```
================================================================================
Performing backup on http://****:****@127.0.0.1:5984/_users using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/pr/7r562dtd7q5dnkg_wx6tfwsm0000gn/T/tmp-64420J7fv9cD0GiJ5.tmp",
  "mode": "full",
  "parallelism": 5
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Total batches received: 1 +95ms
@cloudant/couchbackup/includes/backup.js:231
          body.results.forEach(function(d) {
                       ^

TypeError: Cannot read property 'forEach' of undefined
```

## Environment details

node -v -> v8.9.4
cloudant developer docker image from: https://hub.docker.com/r/ibmcom/cloudant-developer/

**Comment by sballesteros** [comment] 2018-10-11 03:07
Actually i am getting the same error when targeting a remote database on Cloudant (IBM bluemix)

**Comment by ricellis** [comment] 2018-10-11 09:49
This appears to be a server side problem as the server is sending back an incomplete JSON object:
```
{"results": 
```
This is true for Apache CouchDB 2.x also, although the behaviour is slightly different, we're investigating why this is.

In the meantime you could do a [shallow mode backup](https://github.com/cloudant/couchbackup#what-is-shallow-mode) of the `_users` DB as it uses `_all_docs` instead of `_bulk_get`, but is limited to the winning revision only.

**Comment by emlaver** [comment] 2018-10-11 17:10
@sballesteros There's a PR in process: https://github.com/apache/couchdb/pull/1650

**Comment by ricellis** [comment] 2018-10-12 09:07
Closing as there is nothing to do in couchbackup for this, the issue is being caused by two server-side issues:
i) `_bulk_get` not working with the `_users` DB apache/couchdb#1650
ii) `_bulk_get` sending a partial JSON response instead of an error message apache/couchdb#1651

**Closed by ricellis** 2018-10-12 09:07 UTC
