### ISSUE TITLE
[COUCHBACKUP] ENOBUFS error while taking DB backup

### ISSUE THREAD

**Issue by JashobantaSahu** [cloudant/couchbackup#344] opened 2021-03-04 05:09 UTC
## Bug Description
I am trying to take periodic shallow backup of my DB everyday and getting `ENOBUFS` issue coming from `couchbackup` command. I have tried --buffer-size 5000, 10000 and now I have it at 2000. But I get error in all 3 conditions.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
I am using below command to take shallow backup
```
couchbackup --url https://$USER_NAME:$PASSWORD@$DB_ACCOUNT_NAME.cloudant.com --buffer-size 2000 --mode shallow --db $db_name | gzip > /db-backup/shallow/$db_backup_name.txt.gz
```
### 2. What you expected to happen
The backup should have completed without any error with right size of backup file
### 3. What actually happened
Before the process completion, it resulted with an error of type ENOBUFS. Please find below logs for your reference
```
Feb 22 08:04:14 cloudant-backup-job-1613952000-46kd9 cloudant-backup-job couchbackup:backup Written batch ID: 2385 Total document revisions written: 4772000 Time: 758.29
Feb 22 08:04:14 cloudant-backup-job-1613952000-46kd9 cloudant-backup-job couchbackup:backup Written batch ID: 2386 Total document revisions written: 4774000 Time: 758.567
Feb 22 08:04:14 cloudant-backup-job-1613952000-46kd9 cloudant-backup-job ERROR ERROR: write ENOBUFS
Feb 22 08:46:21 cloudant-backup-job-1613952000-46kd9 cloudant-backup-job File size in Bytes : 2198852078
Feb 22 08:46:21 cloudant-backup-job-1613952000-46kd9 cloudant-backup-job Encrypting the file db_backup_file.txt.gz
```

## Environment details
The job is running on Kubernetes as a cron job with:
Node JS version: node:14-alpine
couchbackup version: My DevOps script contains below command which downloads latest stable version of the same
```
npm install -g @cloudant/couchbackup
```

**Comment by eiri** [comment] 2021-03-04 13:38
It seems that you are getting over `buffer.constants.MAX_LENGTH` which is in node [~2GB](https://nodejs.org/api/all.html#buffer_buffer_constants_max_length). This is node's limitation.

I suggest to reduce value of `--buffer-size` further below, maybe starting from the default 500. To be clear, this is not node's buffer in MBytes, this is the number of documents fetched and restored at once, so you need to calculate, based on an average size of your document, a batch size that'll stay below `MAX_LENGTH`.

**Comment by JashobantaSahu** [comment] 2021-03-05 04:55
Thanks for your comment @eiri , please find below few details which can help us in getting down to the exact issue
 - Average size of each document is Approx. 1.5 KB
So considering 2000 documents fetch at once can consume hardly 2.5 MB of buffer space

**Comment by eiri** [comment] 2021-03-16 15:31
@JashobantaSahu so, I tried to reproduce this failure on a similar test database (1.5k per doc, 5M docs) with `node:14-alpine` docker image and it works fine for me, so I guess this is something specific for your environment. Can you please tell me more details on how exactly it is set? What is "DevOps script" you've mentioned, where do you save your backup and how your Dockerfile looks like - I see a line "Encrypting the file db_backup_file.txt.gz", so I assume you have some additional steps there apart from plain `couchbackup` run?

**Comment by eiri** [comment] 2021-08-31 14:07
@JashobantaSahu I'm going to close this issue. There have been a couple of releases since you opened the issue including engine upgrade, so hopefully this problem is gone. Otherwise feel free to reopen it with more details for your specific setup.

**Closed by eiri** 2021-08-31 14:07 UTC
