### ISSUE TITLE
Spurious async.js "Callback was already called." error when doing a backup.

### ISSUE THREAD

**Issue by petervansickel** [cloudant/couchbackup#213] opened 2018-03-30 10:52 UTC
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) 2.2.0
- Node.js version.  v8.9.3
- A sample of the code or command line statement that demonstrates the issue.
I get the stack dump shown below when doing a backup.  It seems to be a harmless error because all backups complete.

Here is the couchbackup code snippet.
for dbname in $dbnames; do
  couchbackup --url "${cloudantURL}" --log "$backupDir/$dbname-backup.log" --db $dbname > "$backupDir/$dbname-backup.json"
done

2018-03-30T10:27:58.774Z couchbackup:backup Fetching all database changes...
2018-03-30T10:27:58.907Z couchbackup:backup Total batches received: 1
/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:985:32
    at next (/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:3589:25)
    at /usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:3363:26
    at Object.processState (/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/lib/clientutils.js:111:7)
    at /usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/lib/client.js:342:17
    at /usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:484:16
    at replenish (/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:1015:17)
    at /usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/node_modules/async/dist/async.js:988:16
    at updateState (/usr/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/lib/clientutils.js:53:3)

**Comment by ricellis** [comment] 2018-04-10 10:40
This is a duplicate of #207.

**Closed by ricellis** 2018-04-10 10:40 UTC
Labels: duplicate
