### ISSUE TITLE
Impossible to restore backedup file

### ISSUE THREAD

**Issue by TatyanaBol** [cloudant/couchbackup#227] opened 2018-05-28 09:08 UTC
- couchbackup/couchrestore version(s) that are affected by this issue. - **latest**
- Node.js version. - 8.11.1
- A sample of the code or command line statement that demonstrates the issue.

I'm trying to use npm package "@cloudant/couchbackup" in my js code.
When I backup db it creates file and finished successfully.
When I try to restore db from this file I get an error:
```
BackupFileJsonError: Error on line 1 of backup file - cannot parse as JSON
    at Transform.writer._transform (../cloudant-backup-restore-scripts/node_modules/@cloudant/couchbackup/includes/writer.js:157:26)
    at Transform._read (_stream_transform.js:186:10)
```
When I backup the db in my code with "exec command couchbackup" (cli), I succeed to restore the db from this file. It means that function  couchbackup.backup() and cli command couchbackup works differently.

The file created by cli command much bigger that the created by function.
It seems the first contains deleted documents and the second - no.
I tried to run the function with opts { mode: 'full'}, it made no difference

Please advice
Tatyana

**Comment by tomblench** [comment] 2018-05-29 12:39
We'll need to see your code and ideally the "good" and "bad" backup files. If you don't want to share these publicly then please get in touch via slack or support@cloudant.com. Without seeing these it's just guesswork at the moment.

**Comment by TatyanaBol** [comment] 2018-05-29 13:50
My code:
```
async function backupDbToFile(config, directory, dbInfo) {
    console.log(`Starting to backup "${dbInfo.dbName}"`);
    const fileName = `${directory}/${dbInfo.dbName}.json`;
    const dbUrl = `https://${dbInfo.apiKey}:${dbInfo.pass}@${config.host}/${dbInfo.dbName}`;
    const stream = fs.createWriteStream(fileName);
    return new Promise((resolve, reject) => {
        couchbackup.backup(dbUrl, stream, (err) => {
                if (err) {
                    return reject(err);
                }
                console.log(`Creating backup for db "${dbInfo.dbName}" has been completed.`);
                resolve();
            }
        );
    });
}
```

**Comment by TatyanaBol** [comment] 2018-05-29 14:07
The details are sent

**Comment by TatyanaBol** [comment] 2018-05-29 14:37
The files are too big, mail delivery failed.
There:
Code of the first option:
```
async function backupDbToFile(config, directory, dbInfo) {
    console.log(`Starting to backup "${dbInfo.dbName}"`);
    const fileName = `${directory}/${dbInfo.dbName}.json`;
    const dbUrl = `https://${dbInfo.apiKey}:${dbInfo.pass}@${config.host}/${dbInfo.dbName}`;
    const stream = fs.createWriteStream(fileName);
    return new Promise((resolve, reject) => {
        couchbackup.backup(dbUrl, stream, (err) => {
                if (err) {
                    return reject(err);
                }
                console.log(`Creating backup for db "${dbInfo.dbName}" has been completed.`);
                resolve();
            }
        );
    });
}
```
The second option:
```
async function backupDbToFile2(config, directory, dbInfo) {
    console.log(`Starting to backup "${dbInfo.dbName}"`);
    const fileName = `${directory}/${dbInfo.dbName}.json`;
    const dbUrl = `https://${dbInfo.apiKey}:${dbInfo.pass}@${config.host}`;
    const command = `couchbackup --url ${dbUrl} --db ${dbInfo.dbName} > ${fileName}`;
    await utils.executeCommand(command);
    console.log(`Creating backup for db "${dbInfo.dbName}" has been completed.`);
}
```
The first file starts with many rows []\n and its size 27.9 MB
The second doesn't contain rows with empty array and its size 36.4 MB

**Comment by tomblench** [comment] 2018-05-29 14:47
What version are you running? Please run `./bin/couchbackup.bin.js -V` and paste the version.

Does your "bad" backup file always have the same contents on each run, or do the exact contents and the positions of the empty arrays change each time?

**Comment by tomblench** [comment] 2018-05-30 12:20
Closing as duplicate of #110 - user was doing multiple concurrent backups.

**Closed by tomblench** 2018-05-30 12:20 UTC
