### ISSUE TITLE
Couchbackup returns empty file

### ISSUE THREAD

**Issue by BennyHoang** [cloudant/couchbackup#331] opened 2020-05-19 16:21 UTC
I created a tool in March that fetches all the name of the databases and writing its content to a file. This has been working until now, where i tried to run the application again. 

This is the function for backing up:

``` javascript
export function couchBackup() {
    initDB().then((result) => {
        for (const item of result) {
            couchbackup.backup(dbUrl + '/' + item, fs.createWriteStream(item + '.json'),
                { parallelism: 2 },
                (err, data) => {
                    if (err) {
                        console.log('failed!', err);
                    } else {
                        console.log('GREAT successs! ', data);
                    }
                });
        }
    });
}
```
I am still able to go into the cloudant service and i am getting the names of the databases. It is also downloading 1 file for each db as expected, but this time this is empty. It doesn't look like it is going further to the parralelism:2 line. I don't even get Great success!

- couchbackup version
    2.5.2
- Node.js version
    10.0.0

**Comment by BennyHoang** [comment] 2020-05-19 17:15
So i got the application working now with running the app via git bash. It didn't work with WSL.

**Comment by bessbd** [comment] 2020-05-20 14:34
If I understand correctly, the issue is gone now. I'm about to close this ticket.

> Should it be any difference between "win32" vs "linux" platform when running couchbackup?

There should be no such platform-dependent pieces in the code. If you manage to find any, @BennyHoang , please let us know.

**Closed by bessbd** 2020-05-20 14:34 UTC

**Comment by BennyHoang** [comment] 2020-05-22 19:25
Will keep you updated!

So where i am currently:

```javascript
export function couchBackup() {
    initDB().then((result) => {
        for (const item of result) {
            couchbackup.backup(dbUrl + '/' + item, fs.createWriteStream(item + '.json'),
                //nothinig happens here
                { parallelism: 2 },
                (err, data) => {
                    if (err) {
                        //does not log anything in here
                        console.log('failed!', err);
                    } else {
                        //does not log anything in here
                        console.log('GREAT successs! ', data);
                    }
                });
        }
    });
}
```
So it looks like the application is restarting before it can write the content of the db to thie files.
