### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by wmbutler** [cloudant/couchbackup#264] opened 2018-12-04 04:55 UTC
couchbackup: latest master branch
node: v10.14.1
Changes log file: 2.8GB
--mode full

The changes files gets written but when couchbackup goes to fetch the records, I get this:
```
buffer.js:270
    throw err;
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "3785602604" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:292:3)
    at Function.concat (buffer.js:474:23)
    at Request.<anonymous> (/home/couchbackup/node_modules/request/request.js:1133:30)
    at Request.emit (events.js:187:15)
    at Request.self._source.emit (/home/couchbackup/node_modules/@cloudant/cloudant/lib/eventrelay.js:78:21)
    at Gunzip.<anonymous> (/home/couchbackup/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at Gunzip.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Is this because you are trying to load the log file which is 2.8GB into a node 1GB max buffer? Is there any workaround for this?

**Comment by ricellis** [comment] 2018-12-04 10:54
Please complete the issue template fully when opening issues. In the absence of the complete information from that template I'm going to assume you are using the same options you outlined in your previous issue #262, in particular `--buffer-size 10000`.

>Is this because you are trying to load the log file which is 2.8GB into a node 1GB max buffer?

No, we stream the log file line by line. The buffer in question here is, I believe, the response from the server with the document revisions.

>Is there any workaround for this?

Reduce the `--buffer-size` so that fewer document revisions are being fetched at once so that their total size does not exceed 1GB per batch. Unfortunately this can be a bit trial and error unless your document size and number of revisions is fairly consistent in which case you can make an estimate.

**Comment by wmbutler** [comment] 2018-12-04 16:45
@ricellis thanks for the reply. Just so I understand, if I were to set my buffersize to 2000 and parallel to 5, would this create the same net effect on the buffer  overflow as buffersize 10000 and parallel 1? Understanding this will help me as I tweak the settings.

**Comment by ricellis** [comment] 2018-12-05 10:11
Node's internal 1GB buffer limit should only be impacted by the number of revisions that get fetched at once. Specifically there will be a new `Buffer` for each of the HTTP responses, so as long as the `--buffer-size` is low enough that limit should not be reached. However, the number of HTTP responses being processed in parallel is controlled by the `--parallelism`. The problem then becomes overall memory consumption - so if you managed to choose a `--buffer-size` that results in (decompressed) responses of exactly 1 GB and had `--parallelism 10` you would need _at the very least_ 10 GB of memory available for the response buffers (and significantly more to account for the various other overheads).

See also #170.

**Comment by wmbutler** [comment] 2018-12-05 18:15
I discovered the problem. It's related to your new changeStream function. This was modified since 2.3.1 and it on your master branch. To solve for it, I forked from tag 2.3.1 and added my incremental code to that. Make sure you test your code on a large database before promoting it to the next version.

New version
https://github.com/cloudant/couchbackup/blob/17c8c155f25cfbb414db6158d65eb79c657e152c/includes/spoolchanges.js#L65

2.3.1 version
https://github.com/cloudant/couchbackup/blob/747f6a733df806d93f7f3eacf085303476ff01b5/includes/spoolchanges.js#L65

**Comment by smithsz** [comment] 2018-12-17 11:12
We're unable to reproduce this issue. Can you provide us an example dataset we can use to reproduce this issue? Thanks.

**Comment by wmbutler** [comment] 2018-12-18 14:59
I wish I could, but my data contains PHI. Seems that it was happening for any database over 150GB during the backup process.

**Comment by ricellis** [comment] 2018-12-20 10:41
Thanks @wmbutler we've reproduced the issue now, it is a bug in the [Nano 7.x dependency](https://github.com/apache/couchdb-nano/issues/141). We won't release the new version of couchbackup until that issue is resolved.

I'll leave this issue open because I think we will want to bump our minimum `@cloudant/cloudant` version and it in turn should probably bump it's minimum Nano version to ensure the fix is included.

**Closed** 2019-03-14 11:02 UTC
